# Generated by Django 4.0.1 on 2022-09-26 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_alter_profile_profile_image_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skilll',
        ),
    ]
